sudo: required
language: python
python:
- '2.7'
services:
- docker
install: pip install -U -rrequirements_dev.txt
script:
- tox -e ${TOXENV}
- codecov
env:
- TOXENV=unit
- TOXENV=integration
- TOXENV=lint
notifications:
  slack:
    secure: m93SUlspdjGsGchPECDbBoKAPSABH6z/9G87kXr1X9Of0DSghSoGDHsAmPwu/5SEe5BVFR+tnj44VgCoLC5/4CHxj2BG8ykRy8RAUnGR6p9k+s+qLuk1it7oCiI0skQ5wGdmqcbeHX+wzD7FpBa+Bqz6hRc45bGxmTc4LgADUwX5x9S4kMnz+MtX6JvvUOpZJAJpyvbQPt7Q5KQD1+9uBmigIaiX/eeMNsdZKBa0klEX07bkwNKXR03uqclhxv8l77+kKC+na5zfczGJQ7Ygg515sIPwZUm7BoiCoGeXXXAt52K4Ec9BkHl7UCAWeU6Az8AqDbbWJZHRiZmr0RkSg9ZvvtW1iXCjWoS5tM0rSOr7u+m3bGdVdhYgBnPwcf3H8RUTgy6t2c56sWiEy17LJLXBRiOxPKNawBbGI/WHQqoVfT95klzzHCN9ZGQETDkeZU7xNs/KGrW6UnXI/I34cJ4/L1RM3pVuXuCxgloIw3/w+s9JAv0dj8iNjtYHt3UCrtcJWFEYI1RahPXpNXQM1pWmqIk1CA9CPp9WQdTOoOAXjDX8PTDFnLSlRSpIZ3C8C9avqjiPw+Q3LVH2V/2hOPBX6EzGAhGnIXpqStSrj5oGuegpjBi59Cpk1e3JDZful/HjTIp8S8YvSt8T+yIvXnc47hHLoIGD3AmtwdJH6pE=
deploy:
  provider: pypi
  user: twindb
  password:
    secure: aDLLv5BbnsLC5uukE5GaKjamjO51RrZuOhitG1PeRHz9LZ8orTfo4keFB/KD7Tgo07TMD1T/2nfYOPE2vfaFrJJo+NcKuV1u5yr8+2uY78Dvvvbn+PtYdB1GOaS+wDL5hvdVj9bf2wGF4HA9uPKtwmSuJlJ+mwRUYCk3ZJ+YH/Mhffa3mgp4CVX3IQ+lpEZaeu3zi33fwNlkKngtPDQ4lJslkHXpVq5SLLYvC0wlj0eE2uGK6woJbMO8XwmFC8K32/+fAhqsMZtGthCgIdICVGUwZWn7UAw+fvWyoks5ZlQC7+HtBTlVkfwDsBGjU46q4z5rlQD0kC+9HVP7kvmsJwA+qwxm0icQ+8okhVzaeKd2GMfVeCNhUoyn9UG5IV/mJJNs4ULcjTF6XocduRYrzVh5a4zHq5rPLW6DYP9Zd2l9KQHVRbyxX4U2c7haFpreYxEoZvVdlVnqfWublbbfWyYLQXxi+DC1yiYjHd8cjBwt+uykJqaN0cozPh13UqBRRLslKBx46gK34aBPP5+fY1n1zNyYYvEAStXbp4Vsyjr9sEiSoKS8EB6bRA+EuxtwEG1mybMTnU/AiDc7tq/tH3WcCGoQ9IOOt5a6qDfa+zO8Qd8z0PMkTsfmj1EylFpFWtxFfxnxxzrbxZPBzgpgQNPtSQWO3ZLBL3Khsr8WWl8=
  on:
    condition: $TOXENV == integration
    distributions: sdist bdist_wheel
    repo: twindb/proxysql-tools
    branch: master
  skip_upload_docs: true
