sudo: required
language: python
python:
- '2.7'
services:
- docker
install: pip install -U -rrequirements_dev.txt
script:
- tox -e ${TOXENV}
- codecov
env:
- TOXENV=unit
- TOXENV=integration
- TOXENV=lint
notifications:
  slack:
    secure: m93SUlspdjGsGchPECDbBoKAPSABH6z/9G87kXr1X9Of0DSghSoGDHsAmPwu/5SEe5BVFR+tnj44VgCoLC5/4CHxj2BG8ykRy8RAUnGR6p9k+s+qLuk1it7oCiI0skQ5wGdmqcbeHX+wzD7FpBa+Bqz6hRc45bGxmTc4LgADUwX5x9S4kMnz+MtX6JvvUOpZJAJpyvbQPt7Q5KQD1+9uBmigIaiX/eeMNsdZKBa0klEX07bkwNKXR03uqclhxv8l77+kKC+na5zfczGJQ7Ygg515sIPwZUm7BoiCoGeXXXAt52K4Ec9BkHl7UCAWeU6Az8AqDbbWJZHRiZmr0RkSg9ZvvtW1iXCjWoS5tM0rSOr7u+m3bGdVdhYgBnPwcf3H8RUTgy6t2c56sWiEy17LJLXBRiOxPKNawBbGI/WHQqoVfT95klzzHCN9ZGQETDkeZU7xNs/KGrW6UnXI/I34cJ4/L1RM3pVuXuCxgloIw3/w+s9JAv0dj8iNjtYHt3UCrtcJWFEYI1RahPXpNXQM1pWmqIk1CA9CPp9WQdTOoOAXjDX8PTDFnLSlRSpIZ3C8C9avqjiPw+Q3LVH2V/2hOPBX6EzGAhGnIXpqStSrj5oGuegpjBi59Cpk1e3JDZful/HjTIp8S8YvSt8T+yIvXnc47hHLoIGD3AmtwdJH6pE=
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: twindb_test
  password:
    secure: "Ik+BuDJaAB1JvvRtncNCoOq4ucvwWdsQ/y2/nRLZaW4w4scn9iXkLlHFC/i7npboWNNzTRgkTYBTjw8yIrkML59V7ZKmvZv0Pz/4yZTgAAOa2Dk92Zp9Z7POOCIaJW4RacHh1gsu0XjZ82dpll8e3CA//Oo/Mh9zWb7SO7FM4L6plFoaTXAM6uJmnrwXBnxYzqAw+3ORIObOOplbP6BTDAvM4F8dpgyMKR0b2TxsuiII4bpKNTHwbeU6VIF3EFDINoPgGa0Igl4LuS8kxnkRtC0pI44Pn2EvGiC2ULy5VPfpopBvsdD5PS9LjaKqOh+gkeg/uOlkrbaMETRtaJPrfeQjt4HC0dih5vj48jnhAzQRvwXZhPwx3Ax7IwTg905dbRUZIZHaefzrvYAvltN8h4sn2Yh6GGOF4XTQW7d7raclpHRq2u+BDN8ZSVBdK3DpwgEF90pLTJrujc/dP94M/WPkfTDNRsSB0TafoWx/TPtGdex0yR3Xt7E3nA/zptO8kUiQgyXC/EVnq7rNUONQnnI9LRnTRctqFR+ndocL3dZgvxjiVzgAlfwLmo2vQjtA/Hqgph6MYSEFQ1em9ePS67FqyVEkr0SmvM5+lxqrDA2nhFfs9IIYZDcaB6PuM0fL/BMCqb+kDisqJj+Ff35WPrJcNtJHOoAkiQLvGCEBtEk="
  on:
    condition: $TOXENV == integration
    branch: feature/test-pypi
